import type { Artwork, Collection } from '@/app/types'

export const artworks: Artwork[] = [
  {
    id: '1',
    title: 'Fragmented Harmony',
    imageUrl: '/collections/collection1/fragmented_harmony.jpg',
    info: 'Oil on Canvas 80X100',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-01-28T02:44:33.326Z',
  },

  {
    id: '2',
    title: 'Melody in Fragment',
    imageUrl: '/collections/collection1/melody_in_fragments.jpg',
    info: 'Oil on Canvas 80X100',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-01-28T02:44:33.326Z',
  },

  {
    id: '3',
    title: 'Power',
    imageUrl: '/collections/collection1/power.jpg',
    info: 'Oil on Canvas 80X100',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-01-28T02:44:33.326Z',
  },
  {
    id: '4',
    title: 'The First Prayer',
    imageUrl: '/collections/collection1/the_first_prayer.jpg',
    info: 'Oil on Canvas 50X70',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-01-28T02:44:33.326Z',
  },
  {
    id: '5',
    title: 'Fragments of Eden',
    imageUrl: '/collections/collection1/fragments_of_eden.jpg',
    info: 'Oil on Canvas 80X100',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-01-28T02:44:33.326Z',
  },
  {
    id: '12',
    title: 'Sensual Fracture',
    imageUrl: '/collections/collection1/sensual_fracture.jpg',
    info: 'Oil on Canvas 80X100',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-02-13T09:38:08.048Z',
  },
  {
    id: '13',
    title: 'Celestine',
    imageUrl: '/collections/collection1/celestine.jpg',
    info: 'Oil on Canvas 80X100',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-04-03T08:19:08.556Z',
  },
  {
    id: '14',
    title: 'Unraveled Oath',
    imageUrl: '/collections/collection1/unraveled_oath.jpg',
    info: 'Oil on Canvas 100X80',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-04-03T08:19:08.556Z',
  },
  {
    id: '15',
    title: 'Journey to the Unknown',
    imageUrl: '/collections/collection1/journey_to_the unknown.jpg',
    info: 'Oil on Canvas 80X1000',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-04-03T08:19:08.556Z',
  },

  {
    id: '16',
    title: 'Born from Chaos',
    imageUrl: '/collections/collection1/born_from_chaos.jpg',
    info: 'Oil on Canvas 80X1000',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-04-03T08:19:08.556Z',
  },
  {
    id: '17',
    title: 'Helen’s Curse',
    imageUrl: '/collections/collection1/helen_curse.jpg',
    info: 'Oil on Canvas 80X1000',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-04-03T08:19:08.556Z',
  },
  {
    id: '18',
    title: 'Whispers Behind the Walls',
    imageUrl: '/collections/collection1/whispers_behind_the_walls.jpg',
    info: 'Oil on Canvas 80X1000',
    category: 'collections',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-04-03T08:19:08.556Z',
  },
  {
    id: '6',
    title: 'Fragmented Harmony',
    imageUrl: '/wall/fragmented_harmony.jpg',
    info: '',
    category: 'on the wall',
    collectionId: 'lives-in-motion',
    tags: [],
    date: '2025-01-29T04:39:48.623Z',
  },

  {
    id: '7',
    title: 'Melody in Fragment',
    imageUrl: '/wall/melody_in_fragments.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-01-29T04:39:48.623Z',
  },

  {
    id: '8',
    title: 'Power',
    imageUrl: '/wall/power.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-01-29T04:39:48.623Z',
  },
  {
    id: '9',
    title: 'The First Prayer',
    imageUrl: '/wall/the_first_prayer.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-01-29T04:39:48.623Z',
  },
  {
    id: '10',
    title: 'Fragments of Eden',
    imageUrl: '/wall/fragments_of_eden.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-01-29T04:39:48.623Z',
  },
  {
    id: '11',
    title: 'Sensual Fracture',
    imageUrl: '/wall/sensual_fracture.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-02-13T09:38:08.048Z',
  },
  {
    id: '18',
    title: 'Celestine',
    imageUrl: '/wall/celestine.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-04-03T08:32:19.797Z',
  },
  {
    id: '19',
    title: 'Unraveled Oath',
    imageUrl: '/wall/unraveled_oath.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-04-03T08:32:19.797Z',
  },
  {
    id: '20',
    title: 'Journey to the Unknown',
    imageUrl: '/wall/journey_to_the unknown.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-04-03T08:32:19.797Z',
  },

  {
    id: '21',
    title: 'Born from Chaos',
    imageUrl: '/wall/born_from_chaos.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-04-03T08:32:19.797Z',
  },
  {
    id: '22',
    title: 'Helen’s Curse',
    imageUrl: '/wall/helen_curse.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-04-03T08:32:19.797Z',
  },
  {
    id: '23',
    title: 'Whispers Behind the Walls',
    imageUrl: '/wall/whispers_behind_the_walls.jpg',
    info: '',
    category: 'on the wall',
    tags: [],
    date: '2025-04-03T08:32:19.797Z',
  },
]

export const collections: Collection[] = [
  {
    id: 'lives-in-motion',
    collectionName: 'Lives in Motion',
    collectionDescription:
      'Lives in Motion delves into the timeless narrative of humanity—rooted in the origins of Adam and Eve, the first humans who set life into motion. This collection weaves together the stories of our beginnings and the journey of human existence, from creation to the diversity of careers and lifestyles today. Drawing on 30 years of experience working with people, the artist reflects on how those first steps shaped the paths we walk now. Each piece is a tribute to the resilience, creativity, and spirit of humanity, honoring both our shared origins and the individual stories that define us.',
  },
]
